services:
  apache:
    image: php:8.2-apache
    container_name: apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql_erp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=frojen-fuud-2
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123

volumes:
  mysql_data:
